---
creation_rules:
  - path_regex: \.sops\.env$
    input_type: dotenv
    key_groups:
      - age:
          - age1c8cqpw6gnlrf82ewm2vj0yalzszvtzd0mmk5yzr4nfpqqseynq7q86f3sq
stores:
  yaml:
    indent: 2