FROM ghcr.io/ublue-os/ucore-minimal:stable-zfs@sha256:8cd353f224a26bb8ca6bc47ef0b565e87b85f190bc92e96e9869f09900984ab4

ARG HOST

COPY .sops.yaml /usr/share/sops/

# Apps - Filebrowser
COPY apps/filebrowser/filebrowser.container /usr/share/containers/systemd/
COPY apps/filebrowser/filebrowser.volume /usr/share/containers/systemd/

# Apps - Kopia
COPY apps/kopia/kopia.container /usr/share/containers/systemd/
COPY apps/kopia/kopia-cache.volume /usr/share/containers/systemd/
COPY apps/kopia/kopia-logs.volume /usr/share/containers/systemd/

# Apps - Minio
COPY apps/minio/minio.container /usr/share/containers/systemd/
COPY apps/minio/config.sops.env /usr/share/minio/config.sops.env

# Apps - Node-exporter
COPY apps/node-exporter/node-exporter.container /usr/share/containers/systemd/

# Apps - Podman-exporter
COPY apps/podman-exporter/podman-exporter.container /usr/share/containers/systemd/

# Apps - Resilio-sync
COPY apps/resilio-sync/resilio-sync-claude.container /usr/share/containers/systemd/
COPY apps/resilio-sync/resilio-sync-helene.container /usr/share/containers/systemd/
COPY apps/resilio-sync/resilio-sync-claude.volume /usr/share/containers/systemd/
COPY apps/resilio-sync/resilio-sync-helene.volume /usr/share/containers/systemd/
COPY apps/resilio-sync/config/claude.conf /usr/etc/resilio-sync/claude.conf
COPY apps/resilio-sync/config/helene.conf /usr/etc/resilio-sync/helene.conf

# Apps - Scrutiny-collector
COPY apps/scrutiny-collector/storage.container /usr/share/containers/systemd/scrutiny-collector.container
COPY apps/scrutiny-collector/storage.sops.env /usr/share/scrutiny-collector/config.sops.env

# Apps - Traefik
COPY apps/traefik/traefik.container /usr/share/containers/systemd/
COPY apps/traefik/traefik.volume /usr/share/containers/systemd/
COPY apps/traefik/config.sops.env /usr/share/traefik/config.sops.env
COPY apps/traefik/config/storage.yaml /usr/etc/traefik/traefik.yaml

# Apps - Ucore
COPY apps/ucore/lib/common_utils.sops.sh /usr/share/ucore/common_utils.sops.sh
COPY apps/ucore/ucore-update.sh /usr/sbin/ucore-update.sh

# Apps - Zrepl
COPY apps/zrepl /tmp/apps/zrepl
COPY systemd/zrepl-secrets.service /etc/systemd/system/

COPY systemd/ucore-update* /etc/systemd/system/
COPY systemd/ucore-firewalld-setup-storage.service /etc/systemd/system/ucore-firewalld-setup.service
COPY systemd/ucore-zfs-kernel.service /etc/systemd/system/
COPY systemd/brew* /etc/systemd/system/

COPY scripts /tmp/

RUN /tmp/install.sh && \
    /tmp/post-install.sh && \
    ostree container commit