FROM ghcr.io/ublue-os/ucore-minimal:stable-zfs@sha256:32fc9c5c9ac9b1e9cc20e4aab5e5e549b144d45a64a5cd96dac7cf8d344f7689

COPY .sops.yaml /usr/share/sops/

# Apps - Node-exporter
COPY apps/node-exporter/node-exporter.container /usr/share/containers/systemd/

# Apps - Scrutiny-collector
COPY apps/scrutiny-collector/storage-remote.container /usr/share/containers/systemd/scrutiny-collector.container
COPY apps/scrutiny-collector/storage-remote.sops.env /usr/share/scrutiny-collector/config.sops.env

# Apps - Wireguard
COPY apps/wireguard/wg0-client.sops.conf /usr/share/wireguard/wg0-client.sops.conf
COPY systemd/wg0-client.service /etc/systemd/system/

# Apps - Zrepl
COPY apps/zrepl /tmp/apps/zrepl
COPY systemd/zrepl-secrets.service /etc/systemd/system/


COPY systemd/ucore-update* /etc/systemd/system/
COPY systemd/ucore-firewalld-setup-storage-remote.service /etc/systemd/system/
COPY systemd/ucore-zfs-kernel.service /etc/systemd/system/
COPY systemd/brew* /etc/systemd/system/

COPY scripts /tmp/

RUN /tmp/install-common.sh && \
    /tmp/install-storage-remote.sh && \
    /tmp/post-install-common.sh && \
    /tmp/post-install-storage-remote.sh && \
    ostree container commit