FROM ghcr.io/ublue-os/ucore-minimal:stable-zfs@sha256:2d935c39255b2bcd92b511b997826f3477f0aedc12315bfc06728bcaf55426b7

ARG HOST

COPY .sops.yaml /usr/share/sops/

# Apps - Minio
COPY apps/minio/minio.container /usr/share/containers/systemd/
COPY apps/minio/config.sops.env /usr/share/minio/config.sops.env

# Apps - NFS-server
COPY apps/nfs-server/nas-shares.exports /usr/etc/exports/nas-shares.exports

# Apps - Node-exporter
COPY apps/node-exporter/node-exporter.container /usr/share/containers/systemd/

# Apps - Podman-exporter
COPY apps/podman-exporter/podman-exporter.container /usr/share/containers/systemd/

# Apps - Resticprofile
COPY apps/resticprofile/profiles.yaml /usr/local/share/resticprofile/profiles.yaml
COPY apps/resticprofile/repository.sops.key /usr/share/resticprofile/repository.sops.key
COPY apps/resticprofile/resticprofile.sops.env /usr/share/resticprofile/resticprofile.sops.env
COPY apps/resticprofile/resticprofile-backup.service /etc/systemd/system/
COPY apps/resticprofile/resticprofile-backup.timer /etc/systemd/system/
COPY apps/resticprofile/resticprofile-forget.service /etc/systemd/system/
COPY apps/resticprofile/resticprofile-forget.timer /etc/systemd/system/
COPY apps/resticprofile/resticprofile.sh /usr/sbin/resticprofile-backup.sh

# Apps - Scrutiny-collector
COPY apps/scrutiny-collector/storage.container /usr/share/containers/systemd/scrutiny-collector.container
COPY apps/scrutiny-collector/storage.sops.env /usr/share/scrutiny-collector/config.sops.env

# Apps - Traefik
COPY apps/traefik/traefik.container /usr/share/containers/systemd/
COPY apps/traefik/traefik.volume /usr/share/containers/systemd/
COPY apps/traefik/config.sops.env /usr/share/traefik/config.sops.env
COPY apps/traefik/config/storage.yaml /usr/etc/traefik/traefik.yaml

# Apps - Ucore
COPY apps/ucore/lib/common_utils.sops.sh /usr/share/ucore/common_utils.sops.sh
COPY apps/ucore/ucore-update.sh /usr/sbin/ucore-update.sh

# Apps - Zrepl
COPY apps/zrepl /tmp/apps/zrepl
COPY systemd/zrepl-secrets.service /etc/systemd/system/

COPY systemd/ucore-update* /etc/systemd/system/
COPY systemd/ucore-firewalld-setup-storage.service /etc/systemd/system/ucore-firewalld-setup.service
COPY systemd/ucore-zfs-kernel.service /etc/systemd/system/
COPY systemd/brew* /etc/systemd/system/
COPY systemd/nas-* /etc/systemd/system/

COPY scripts /tmp/

RUN /tmp/install.sh && \
    /tmp/post-install.sh && \
    ostree container commit