FROM ghcr.io/ublue-os/ucore-minimal:stable-zfs@sha256:4d0b7032e5bad609286cdcfc1cdbbecce36caa8011cc66b822bc44341cf747b8

ARG HOST

COPY .sops.yaml /usr/share/sops/

# Apps - Node-exporter
COPY apps/node-exporter/node-exporter.container /usr/share/containers/systemd/

# Apps - Scrutiny-collector
COPY apps/scrutiny-collector/storage-remote.container /usr/share/containers/systemd/scrutiny-collector.container
COPY apps/scrutiny-collector/storage-remote.sops.env /usr/share/scrutiny-collector/config.sops.env

# Apps - Ucore
COPY apps/ucore/lib/common_utils.sops.sh /usr/share/ucore/common_utils.sops.sh
COPY apps/ucore/ucore-update.sh /usr/sbin/ucore-update.sh

# Apps - Wireguard
COPY apps/wireguard/wg0-client.sops.conf /usr/share/wireguard/wg0-client.sops.conf
COPY systemd/wg0-client.service /etc/systemd/system/

# Apps - Zrepl
COPY apps/zrepl /tmp/apps/zrepl
COPY systemd/zrepl-secrets.service /etc/systemd/system/


COPY systemd/ucore-update* /etc/systemd/system/
COPY systemd/ucore-firewalld-setup-storage-remote.service /etc/systemd/system/ucore-firewalld-setup.service
COPY systemd/ucore-zfs-kernel.service /etc/systemd/system/
COPY systemd/brew* /etc/systemd/system/

COPY scripts /tmp/

RUN /tmp/install.sh && \
    /tmp/post-install.sh && \
    ostree container commit