---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:

  default:
    cmd: go-task -l
    silent: true

  ignition:
    desc: Generate from butane
    cmds:
      - podman run --rm -v ./:/config:z quay.io/coreos/butane:release --pretty --strict /config/{{.CLI_ARGS}}.bu --files-dir=/config > ./{{.CLI_ARGS}}.ign
