---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:

  default:
    cmd: go-task -l
    silent: true

  butane:
    desc: Generate from butane
    cmds:
      - podman run --rm -v ./butane/{{.CLI_ARGS}}:/config:z quay.io/coreos/butane:release --pretty --strict /config/config.bu --files-dir=/config > ./butane/{{.CLI_ARGS}}/config.ign
