global:
  logging:
    - type: syslog
      format: human
      level: warn
  monitoring:
    - type: prometheus
      listen: :9811
jobs:
- name: push_default
  type: push
  connect:
    type: tls
    address: storage-remote.feisar.ovh:8888
    ca: /etc/zrepl/storage-remote.crt
    cert: /etc/zrepl/storage.crt
    key:  /etc/zrepl/storage.key
    server_cn: storage-remote
  filesystems: {
    "vol1<": true,
    "vol1/apps/frigate<": false,
    "vol1/video<": false,
    "vol2<": true,
  }
  snapshotting:
    type: periodic
    interval: 720m
    prefix: zrepl_push_default_
    timestamp_format: dense
  pruning:
    keep_sender:
    - type: not_replicated
    - type: last_n
      count: 28 # 14 days
    keep_receiver:
      - type: grid
        regex: ^zrepl_.*
        grid: 1x1h(keep=all) | 24x1h | 35x1d | 6x30d
- name: local_video
  type: snap
  filesystems: {
    "vol1/video<": true,
  }
  snapshotting:
    type: periodic
    interval: 720m
    prefix: zrepl_video_
    timestamp_format: dense
  pruning:
    keep:
      - type: last_n
        regex: ^zrepl_video_.*
        count: 20 # 10 days