global:
  logging:
    - type: syslog
      format: human
      level: warn
  monitoring:
    - type: prometheus
      listen: :9811
jobs:
- name: sink
  type: sink
  serve:
      type: tls
      listen: :8888
      ca: /etc/zrepl/storage.crt
      cert: /etc/zrepl/storage-remote.crt
      key: /etc/zrepl/storage-remote.key
      client_cns:
        - storage
  root_fs: vol1