global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO

providers:
  file:
    filename: /etc/traefik/traefik.yaml
    watch: true
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false

tls:
  options:
    default:
      sniStrict: true
      minVersion: VersionTLS13

api:
  dashboard: true
  insecure: true
  debug: true

certificatesResolvers:
  letsencryptStaging:
    acme:
      storage: /data/acme.json
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: ovh
        delaybeforecheck: 10
        disablepropagationcheck: true
  letsencryptProduction:
    acme:
      storage: /data/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: ovh
        delaybeforecheck: 10
        disablepropagationcheck: true
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
    asDefault: true
    http:
      tls:
        certResolver: letsencryptProduction

serversTransport:
  insecureSkipVerify: true

http:
  routers:
    dashboard:
      # Catch any '/traefik' prefixed path or any request that has got a 'Referer' header set to '/traefik'
      rule: Host(`storage.feisar.ovh`) && PathPrefix(`/traefik/`) || HeaderRegexp(`Referer`, `.*/traefik/.*`)
      # this rule should be evaluated before any other potential request to '/api' having no Referer header
      priority: 999
      entryPoints: [websecure]
      middlewares:
        - traefik-mid
      service: api@internal

  middlewares:
    # Because the traefik api and dashboard have hardcoded path prefixes /api and /dashboard, strip the '/traefik' path prefix.
    traefik-mid:
      stripPrefix:
        prefixes:
          - /traefik
