---
ports:
  dns: 0.0.0.0:53
  http: 0.0.0.0:4000

upstreams:
  groups:
    default:
      - tcp-tls:1.1.1.1:853
      - tcp-tls:1.0.0.1:853

clientLookup:
  upstream: 192.168.1.123:53 # bind

ecs:
  useAsClient: true

prometheus:
  enable: true
  path: /metrics

blocking:
  loading:
    downloads:
      timeout: 4m
  blackLists:
    ads:
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/pro.txt
      - |
        *.androidtvchannels-pa.googleapis.com
        *.androidtvwatsonfe-pa.googleapis.com
    threats:
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/tif.txt
  whiteLists:
    ads:
      - |
        *.amazonaws.com
  clientGroupsBlock:
    default:
      - ads
      - threats
